name: deploy to production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: Lorddistrict/Prometheus
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        - name: Deploy prod
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_SERVER }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd prometheus
              git pull
              kubectl apply -f k8s